name: Deploy to CloudPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 77.37.44.209 >> ~/.ssh/known_hosts

    - name: Deploy to CloudPanel
      run: ssh -o StrictHostKeyChecking=no hannahasaindonesia-app@77.37.44.209 "cd /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com && ./deploy.sh"
