name: Deploy to Main

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch
      - name: Checkout main
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Mengatur versi Node.js ke 16

      # Connect to VPS and run deployment commands
      - name: Connect to VPS
        uses: appleboy/ssh-action@v0.1.0  # Spesifikasikan versi untuk stabilitas
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}  # Tetap menggunakan password
          port: 22
          script: |
            # Check if the directory exists and if it contains a Git repository
            if [ ! -d "/home/techbyzeyn-app/htdocs/app.techbyzeyn.io/.git" ]; then
              # Clone the private repository if it does not exist
              git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/muhzhen/hannah-course.git /home/techbyzeyn-app/htdocs/app.techbyzeyn.io/
            else
              # If the repository exists, set up the remote origin
              cd /home/techbyzeyn-app/htdocs/app.techbyzeyn.io/
              git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/muhzhen/hannah-course.git
            fi

            # Change to the application directory
            cd /home/techbyzeyn-app/htdocs/app.techbyzeyn.io/
            git config pull.rebase false
            git pull origin main
