name: Deploy to Main

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch
      - name: Checkout main
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Mengatur versi Node.js ke 16

      # Connect to VPS and run deployment commands
      - name: Connect to VPS
        uses: appleboy/ssh-action@v0.1.0  # Spesifikasikan versi untuk stabilitas
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            # Check if the directory exists and if it contains a Git repository
            if [ ! -d "/home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/.git" ]; then
              # Clone the private repository if it does not exist
              echo "Cloning repository..."
              git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/muhzhen/hannah-course.git /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/
            else
              echo "Repository already exists. Checking remote configuration..."
              cd /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/

              # Check if remote 'origin' exists
              if git remote get-url origin > /dev/null 2>&1; then
                echo "Remote 'origin' exists. Pulling latest changes..."
              else
                echo "Remote 'origin' not found. Setting it up..."
                git remote add origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/muhzhen/hannah-course.git
              fi

              # Configure credentials
              git config --global credential.helper store
              echo "https://$GITHUB_ACTOR:${{ secrets.PERSONAL_ACCESS_TOKEN }}" > ~/.git-credentials
            fi

            # Change to the application directory and pull changes
            cd /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/
            git config pull.rebase false

            # Pull the latest changes
            git pull origin main || { echo "Failed to pull from remote repository"; exit 1; }
