name: Deploy to Main

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch
      - name: Checkout main
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Mengatur versi Node.js ke 16

      # Connect to VPS and run deployment commands
      - name: Connect to VPS
        uses: appleboy/ssh-action@v0.1.0  # Spesifikasikan versi untuk stabilitas
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}  # Tetap menggunakan password
          port: 22
          script: |
            # Add GitHub to known hosts to avoid host key verification failed error
            echo "Adding GitHub to known hosts..."
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            # Check if the directory exists and if it contains a Git repository
            if [ ! -d "/home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/.git" ]; then
              # Clone the repository if it does not exist
              echo "Cloning repository..."
              git clone git@github.com:muhzhen/hannah-course.git /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/
            else
              echo "Repository already exists. Checking remote configuration..."
              cd /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/

              # Verify if the remote 'origin' exists
              if git remote get-url origin > /dev/null 2>&1; then
                echo "Remote 'origin' exists. Changing to SSH..."
                # Change the remote URL to use SSH
                git remote set-url origin git@github.com:muhzhen/hannah-course.git
              else
                echo "Remote 'origin' not found. Setting it up..."
                git remote add origin git@github.com:muhzhen/hannah-course.git
              fi

              # Pull the latest changes
              git config pull.rebase false
              git pull origin main || { echo "Failed to pull from remote repository"; exit 1; }
            fi
