name: Deploy to Main

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # mengambil (download) versi terbaru kode dari branch main
      - name: Checkout main
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Mengatur versi Node.js ke 16

      # Koneksi ke vps untuk menjalankan deployment
      - name: Connect to VPS
        uses: appleboy/ssh-action@v0.1.0  # Spesifikasikan versi untuk stabilitas
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            # Cek apakah direktori tersebut ada dan apakah di dalamnya terdapat repository Git.
            if [ ! -d "/home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/.git" ]; then
              # Clone the repository using Personal Access Token
              git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/muhzhen/hannah-course.git /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/
            fi

            # Berpindah ke direktori aplikasi
            cd /home/hannahasaindonesia-app/htdocs/app.hannahasaindonesia.com/

            # Mengatur konfigurasi git agar pull tidak menggunakan rebase
            git config pull.rebase false

            # Menarik perubahan terbaru dari branch 'main' di GitHub
            git pull origin main
